-- ============================================================================
-- Portal de Organograma — INC | Seeds canônicas (base v2)
-- Fontes oficiais: Organograma_Institucional_v2.xlsx + tabela de Famílias de
-- Nível Hierárquico. Rodar DEPOIS de 01_schema.sql (estrutura v2).
-- ============================================================================
SET NAMES utf8mb4;

-- nivel_hierarquico: 44 famílias (NH500–NH544). ordem 1–18 (1 = topo);
-- várias famílias compartilham a mesma ordem (variação A–L).
INSERT INTO nivel_hierarquico (id, codigo_nh, ordem, variacao, cod_var, familia) VALUES
(UUID(), 'NH500', 1, 'A', '1.A', 'Presidente'),
(UUID(), 'NH501', 1, 'A', '1.A', 'Conselheiro'),
(UUID(), 'NH502', 3, 'A', '3.A', 'CFO'),
(UUID(), 'NH503', 4, 'A', '4.A', 'Diretor'),
(UUID(), 'NH504', 5, 'A', '5.A', 'Vice-Diretor'),
(UUID(), 'NH505', 6, 'A', '6.A', 'Gerente'),
(UUID(), 'NH506', 8, 'A', '8.A', 'Coordenador'),
(UUID(), 'NH508', 8, 'B', '8.B', 'Gestor'),
(UUID(), 'NH509', 8, 'C', '8.C', 'Head'),
(UUID(), 'NH510', 9, 'A', '9.A', 'Supervisor'),
(UUID(), 'NH511', 10, 'A', '10.A', 'Encarregado'),
(UUID(), 'NH512', 10, 'B', '10.B', 'Mestre de Obra'),
(UUID(), 'NH513', 11, 'A', '11.A', 'Advogado'),
(UUID(), 'NH514', 11, 'B', '11.B', 'Arquiteto'),
(UUID(), 'NH515', 11, 'C', '11.C', 'Desenvolvedor'),
(UUID(), 'NH516', 11, 'D', '11.D', 'Engenheiro'),
(UUID(), 'NH517', 11, 'E', '11.E', 'Piloto'),
(UUID(), 'NH518', 12, 'A', '12.A', 'Analista'),
(UUID(), 'NH519', 12, 'B', '12.B', 'Comprador'),
(UUID(), 'NH520', 12, 'C', '12.C', 'Designer'),
(UUID(), 'NH521', 13, 'A', '13.A', 'Técnico'),
(UUID(), 'NH522', 13, 'B', '13.B', 'Pedreiro'),
(UUID(), 'NH523', 13, 'C', '13.C', 'Carpinteiro'),
(UUID(), 'NH524', 13, 'D', '13.D', 'Marceneiro'),
(UUID(), 'NH525', 13, 'E', '13.E', 'Armador'),
(UUID(), 'NH526', 13, 'F', '13.F', 'Gesseiro'),
(UUID(), 'NH527', 13, 'G', '13.G', 'Pintor'),
(UUID(), 'NH528', 13, 'H', '13.H', 'Encanador'),
(UUID(), 'NH529', 13, 'I', '13.I', 'Bombeiro Hidráulico'),
(UUID(), 'NH530', 13, 'J', '13.J', 'Eletricista'),
(UUID(), 'NH531', 13, 'K', '13.K', 'Instalador'),
(UUID(), 'NH532', 13, 'L', '13.L', 'Operador'),
(UUID(), 'NH533', 14, 'A', '14.A', 'Assessor'),
(UUID(), 'NH534', 14, 'B', '14.B', 'Assistente'),
(UUID(), 'NH535', 14, 'C', '14.C', 'Captador'),
(UUID(), 'NH536', 14, 'D', '14.D', 'Almoxarife'),
(UUID(), 'NH537', 14, 'E', '14.E', 'Secretária'),
(UUID(), 'NH538', 15, 'A', '15.A', 'Auxiliar'),
(UUID(), 'NH539', 15, 'B', '15.B', 'Meio Oficial'),
(UUID(), 'NH540', 15, 'C', '15.C', 'Sinaleiro'),
(UUID(), 'NH541', 16, 'A', '16.A', 'Estagiário'),
(UUID(), 'NH542', 17, 'A', '17.A', 'Aprendiz'),
(UUID(), 'NH543', 17, 'B', '17.B', 'Porteiro'),
(UUID(), 'NH544', 18, 'A', '18.A', 'Servente');

-- situacao: 10 oficiais (código-letra do DP). Todas visíveis na árvore
-- (a base não traz inativos/desligados).
INSERT INTO situacao (id, codigo_dp, nome, nome_normalizado, ativo_na_arvore) VALUES
(UUID(), 'A', 'Ativo', 'ativo', 1),
(UUID(), 'V', 'Aviso Prévio', 'aviso previo', 1),
(UUID(), 'F', 'Férias', 'ferias', 1),
(UUID(), 'E', 'Licença Mater.', 'licenca mater.', 1),
(UUID(), 'T', 'Af.Ac.Trabalho', 'af.ac.trabalho', 1),
(UUID(), 'P', 'Af.Previdência', 'af.previdencia', 1),
(UUID(), 'C', 'Contrato de Trabalho Suspenso', 'contrato de trabalho suspenso', 1),
(UUID(), 'I', 'Apos. por Incapacidade Permanente', 'apos. por incapacidade permanente', 1),
(UUID(), 'U', 'Outros', 'outros', 1),
(UUID(), 'Q', 'Prisão / Cárcere', 'prisao / carcere', 1);

-- setor: 40 áreas com código oficial (SET…).
INSERT INTO setor (id, codigo_dp, nome, nome_normalizado) VALUES
(UUID(), 'SET300', 'Obra', 'obra'),
(UUID(), 'SET301', 'Controladoria Gerencial', 'controladoria gerencial'),
(UUID(), 'SET302', 'Administrativo', 'administrativo'),
(UUID(), 'SET303', 'Segurança do Trabalho', 'seguranca do trabalho'),
(UUID(), 'SET304', 'Tecnologia da Informação', 'tecnologia da informacao'),
(UUID(), 'SET305', 'Contabilidade e Fiscal', 'contabilidade e fiscal'),
(UUID(), 'SET306', 'Crédito Imobiliário - Engenharia', 'credito imobiliario - engenharia'),
(UUID(), 'SET307', 'Controladoria Administrativa', 'controladoria administrativa'),
(UUID(), 'SET308', 'Assistência Técnica', 'assistencia tecnica'),
(UUID(), 'SET309', 'Suprimentos', 'suprimentos'),
(UUID(), 'SET310', 'Jurídico', 'juridico'),
(UUID(), 'SET311', 'DSE e Contratos', 'dse e contratos'),
(UUID(), 'SET312', 'Conciliação Financeira', 'conciliacao financeira'),
(UUID(), 'SET313', 'Projetos e Arquitetura', 'projetos e arquitetura'),
(UUID(), 'SET314', 'Cobrança', 'cobranca'),
(UUID(), 'SET315', 'Departamento Pessoal', 'departamento pessoal'),
(UUID(), 'SET316', 'Orçamento', 'orcamento'),
(UUID(), 'SET317', 'Planejamento Financeiro', 'planejamento financeiro'),
(UUID(), 'SET318', 'Projetos Executivos', 'projetos executivos'),
(UUID(), 'SET319', 'Comercial', 'comercial'),
(UUID(), 'SET320', 'Recursos Humanos', 'recursos humanos'),
(UUID(), 'SET321', 'Qualidade', 'qualidade'),
(UUID(), 'SET322', 'Marketing', 'marketing'),
(UUID(), 'SET323', 'Contas a Receber', 'contas a receber'),
(UUID(), 'SET324', 'Licenciamento', 'licenciamento'),
(UUID(), 'SET325', 'Presidência', 'presidencia'),
(UUID(), 'SET326', 'Controle e Planejamento de Obra', 'controle e planejamento de obra'),
(UUID(), 'SET327', 'Relacionamento com Cliente', 'relacionamento com cliente'),
(UUID(), 'SET328', 'Aeronaves', 'aeronaves'),
(UUID(), 'SET329', 'Contas a Pagar', 'contas a pagar'),
(UUID(), 'SET330', 'Novos Negócios', 'novos negocios'),
(UUID(), 'SET332', 'Crédito Imobiliário - Comercial', 'credito imobiliario - comercial'),
(UUID(), 'SET331', 'Registro de Incorporação', 'registro de incorporacao'),
(UUID(), 'SET333', 'Conselho Administrativo', 'conselho administrativo'),
(UUID(), 'SET334', 'Financeiro', 'financeiro'),
(UUID(), 'SET335', 'Engenharia', 'engenharia'),
(UUID(), 'SET336', 'Desenvolvimento Imobiliário', 'desenvolvimento imobiliario'),
(UUID(), 'SET337', 'Design de Processos', 'design de processos'),
(UUID(), 'SET338', 'Governança e Gestão Administrativa', 'governanca e gestao administrativa'),
(UUID(), 'SET339', 'Administrativo - Presidência', 'administrativo - presidencia');

-- local_trabalho: 41 locais com código oficial (LOCTRA…).
INSERT INTO local_trabalho (id, codigo_dp, nome, nome_normalizado) VALUES
(UUID(), 'LOCTRA200', 'Obra - Park Espanha', 'obra - park espanha'),
(UUID(), 'LOCTRA201', 'Obra - UpSide Rio Branco', 'obra - upside rio branco'),
(UUID(), 'LOCTRA202', 'Obra - Reserva Realeza', 'obra - reserva realeza'),
(UUID(), 'LOCTRA203', 'Obra - Reserva JK', 'obra - reserva jk'),
(UUID(), 'LOCTRA204', 'Obra - Unique Sollare', 'obra - unique sollare'),
(UUID(), 'LOCTRA205', 'Obra - Palestra', 'obra - palestra'),
(UUID(), 'LOCTRA206', 'Obra - Reserva Por do Sol', 'obra - reserva por do sol'),
(UUID(), 'LOCTRA207', 'Rossi - Administrativo Backoffice', 'rossi - administrativo backoffice'),
(UUID(), 'LOCTRA208', 'Obra - UpSide Rio Preto', 'obra - upside rio preto'),
(UUID(), 'LOCTRA209', 'Obra - Smart Garden', 'obra - smart garden'),
(UUID(), 'LOCTRA210', 'Obra - Reserva Aurora', 'obra - reserva aurora'),
(UUID(), 'LOCTRA211', 'Obra - Unique Palestra', 'obra - unique palestra'),
(UUID(), 'LOCTRA212', 'Obra - Life São José', 'obra - life sao jose'),
(UUID(), 'LOCTRA213', 'Obra - Reserva Andorinhas', 'obra - reserva andorinhas'),
(UUID(), 'LOCTRA214', 'Obra - Emotion 5', 'obra - emotion 5'),
(UUID(), 'LOCTRA215', 'Obra - Felicitá São José', 'obra - felicita sao jose'),
(UUID(), 'LOCTRA216', 'Obra - Millenium São José', 'obra - millenium sao jose'),
(UUID(), 'LOCTRA217', 'Obra - Palestra Life', 'obra - palestra life'),
(UUID(), 'LOCTRA218', 'Obra - São Pedro Life', 'obra - sao pedro life'),
(UUID(), 'LOCTRA219', 'Obra - Emotion III', 'obra - emotion iii'),
(UUID(), 'LOCTRA220', 'Obra - Unique Jardins', 'obra - unique jardins'),
(UUID(), 'LOCTRA221', 'Obra - Reserva Bela Vista II', 'obra - reserva bela vista ii'),
(UUID(), 'LOCTRA222', 'Obra - Park Primavera', 'obra - park primavera'),
(UUID(), 'LOCTRA223', 'Obra - Unique Sabiá', 'obra - unique sabia'),
(UUID(), 'LOCTRA224', 'Obra - Paraíso', 'obra - paraiso'),
(UUID(), 'LOCTRA225', 'Obra - Upside', 'obra - upside'),
(UUID(), 'LOCTRA226', 'Obra - Karaíba', 'obra - karaiba'),
(UUID(), 'LOCTRA227', 'Obra - Reserva Barcelona', 'obra - reserva barcelona'),
(UUID(), 'LOCTRA228', 'Obra - Benfica', 'obra - benfica'),
(UUID(), 'LOCTRA229', 'Obra - Unique São José', 'obra - unique sao jose'),
(UUID(), 'LOCTRA230', 'Comercial - Itinerante', 'comercial - itinerante'),
(UUID(), 'LOCTRA231', 'Obra - São José do Rio Preto', 'obra - sao jose do rio preto'),
(UUID(), 'LOCTRA232', 'Aeronaves - Itinerante', 'aeronaves - itinerante'),
(UUID(), 'LOCTRA233', 'Segurança do Trabalho - Marilândia', 'seguranca do trabalho - marilandia'),
(UUID(), 'LOCTRA234', 'Novos Negócios - Uberlândia', 'novos negocios - uberlandia'),
(UUID(), 'LOCTRA235', 'Novos Negócios - Uberaba', 'novos negocios - uberaba'),
(UUID(), 'LOCTRA236', 'Comercial - São João Del Rei', 'comercial - sao joao del rei'),
(UUID(), 'LOCTRA237', 'Segurança do Trabalho - Uberlândia', 'seguranca do trabalho - uberlandia'),
(UUID(), 'LOCTRA238', 'Obra - Unique Sollare II', 'obra - unique sollare ii'),
(UUID(), 'LOCTRA239', 'Obra - Reserva Bela Vista I', 'obra - reserva bela vista i'),
(UUID(), 'LOCTRA240', 'Obra - Central Park', 'obra - central park');

-- regional: 6.
INSERT INTO regional (id, nome, nome_normalizado) VALUES
(UUID(), 'Uberlândia', 'uberlandia'),
(UUID(), 'Juiz De Fora', 'juiz de fora'),
(UUID(), 'São José Dos Campos', 'sao jose dos campos'),
(UUID(), 'São Jose Do Rio Preto', 'sao jose do rio preto'),
(UUID(), 'Uberaba', 'uberaba'),
(UUID(), 'São João Del Rei', 'sao joao del rei');

-- cargo: 150. codigo_cargo_dp é anotação (não-único). nivel_id resolvido
-- a partir do Cod. Nivel Hierarquia (NH) via tabela auxiliar.
INSERT INTO cargo (id, codigo_cargo_dp, nome, nome_normalizado, nivel_id) VALUES
(UUID(), '117', 'Servente de Obra', 'servente de obra', NULL),
(UUID(), '108', 'Pedreiro de Acabamento', 'pedreiro de acabamento', NULL),
(UUID(), '95', 'Gesseiro', 'gesseiro', NULL),
(UUID(), '4', 'Almoxarife', 'almoxarife', NULL),
(UUID(), '76', 'Encarregado de Instalações', 'encarregado de instalacoes', NULL),
(UUID(), '19', 'Analista de Planejamento Financeiro', 'analista de planejamento financeiro', NULL),
(UUID(), '29', 'Armador', 'armador', NULL),
(UUID(), '115', 'Servente de Limpeza', 'servente de limpeza', NULL),
(UUID(), '112', 'Porteiro', 'porteiro', NULL),
(UUID(), '101', 'Mestre de Obra', 'mestre de obra', NULL),
(UUID(), '118', 'Sinaleiro', 'sinaleiro', NULL),
(UUID(), '75', 'Encarregado de Carpinteiro', 'encarregado de carpinteiro', NULL),
(UUID(), '104', 'Operador de Cremalheira', 'operador de cremalheira', NULL),
(UUID(), '103', 'Operador de Betoneira', 'operador de betoneira', NULL),
(UUID(), '77', 'Encarregado de Obra', 'encarregado de obra', NULL),
(UUID(), '132', 'Técnico de Segurança do Trabalho', 'tecnico de seguranca do trabalho', NULL),
(UUID(), '32', 'Assistente Administrativo', 'assistente administrativo', NULL),
(UUID(), '42', 'Assistente de Planejamento e Controle', 'assistente de planejamento e controle', NULL),
(UUID(), '116', 'Servente de Limpeza B', 'servente de limpeza b', NULL),
(UUID(), '126', 'Supervisor de Segurança do Trabalho', 'supervisor de seguranca do trabalho', NULL),
(UUID(), '28', 'Aprendiz', 'aprendiz', NULL),
(UUID(), '70', 'Encanador', 'encanador', NULL),
(UUID(), '51', 'Auxiliar Fiscal', 'auxiliar fiscal', NULL),
(UUID(), '43', 'Auxiliar Administrativo', 'auxiliar administrativo', NULL),
(UUID(), '78', 'Engenheiro Civil', 'engenheiro civil', NULL),
(UUID(), '127', 'Técnico de Engenharia Civil', 'tecnico de engenharia civil', NULL),
(UUID(), '38', 'Assistente de Engenharia', 'assistente de engenharia', NULL),
(UUID(), '61', 'Coordenador de Suprimentos', 'coordenador de suprimentos', NULL),
(UUID(), '2', 'Advogado', 'advogado', NULL),
(UUID(), '137', 'Assistente de Conciliação Financeira', 'assistente de conciliacao financeira', NULL),
(UUID(), '9', 'Analista de Arquitetura', 'analista de arquitetura', NULL),
(UUID(), '55', 'Comprador', 'comprador', NULL),
(UUID(), '49', 'Auxiliar de Departamento Pessoal', 'auxiliar de departamento pessoal', NULL),
(UUID(), '39', 'Assistente de Departamento Pessoal', 'assistente de departamento pessoal', NULL),
(UUID(), '48', 'Auxiliar de Engenharia', 'auxiliar de engenharia', NULL),
(UUID(), '54', 'Carpinteiro', 'carpinteiro', NULL),
(UUID(), '109', 'Pedreiro de Alvenaria', 'pedreiro de alvenaria', NULL),
(UUID(), '131', 'Técnico Orçamentista de Obras', 'tecnico orcamentista de obras', NULL),
(UUID(), '93', 'Gerente de Planejamento Financeiro', 'gerente de planejamento financeiro', NULL),
(UUID(), '26', 'Analista Financeiro', 'analista financeiro', NULL),
(UUID(), '45', 'Auxiliar da Qualidade', 'auxiliar da qualidade', NULL),
(UUID(), '130', 'Analista de Instalações', 'analista de instalacoes', NULL),
(UUID(), '33', 'Assistente da Qualidade', 'assistente da qualidade', NULL),
(UUID(), '7', 'Analista Contábil', 'analista contabil', NULL),
(UUID(), '8', 'Analista da Qualidade', 'analista da qualidade', NULL),
(UUID(), '130', 'Técnico de Obras Civis', 'tecnico de obras civis', NULL),
(UUID(), '66', 'Designer Gráfico', 'designer grafico', NULL),
(UUID(), '68', 'Diretor de Suprimentos', 'diretor de suprimentos', NULL),
(UUID(), '11', 'Analista de Cobrança', 'analista de cobranca', NULL),
(UUID(), '69', 'Eletricista de Instalações', 'eletricista de instalacoes', NULL),
(UUID(), '53', 'Bombeiro Hidráulico', 'bombeiro hidraulico', NULL),
(UUID(), '46', 'Auxiliar de Almoxarifado', 'auxiliar de almoxarifado', NULL),
(UUID(), '78', 'Gerente de Projetos Executivos', 'gerente de projetos executivos', NULL),
(UUID(), '5', 'Analista Administrativo', 'analista administrativo', NULL),
(UUID(), '47', 'Assistente de Compatibilização', 'assistente de compatibilizacao', NULL),
(UUID(), '23', 'Analista de Recursos Humanos', 'analista de recursos humanos', NULL),
(UUID(), '6', 'Analista de Assistência Técnica', 'analista de assistencia tecnica', NULL),
(UUID(), '25', 'Analista de Departamento Pessoal', 'analista de departamento pessoal', NULL),
(UUID(), '18', 'Analista de Meio Ambiente', 'analista de meio ambiente', NULL),
(UUID(), '82', 'Estagiário de Direito', 'estagiario de direito', NULL),
(UUID(), '30', 'Gerente de Arquitetura e Produto', 'gerente de arquitetura e produto', NULL),
(UUID(), '17', 'Analista de Marketing', 'analista de marketing', NULL),
(UUID(), '89', 'Gerente Corporativo de TI', 'gerente corporativo de ti', NULL),
(UUID(), '1', 'Presidente', 'presidente', NULL),
(UUID(), '111', 'Pintor', 'pintor', NULL),
(UUID(), '105', 'Operador de Grua', 'operador de grua', NULL),
(UUID(), '26', 'Analista de Conciliação Financeira', 'analista de conciliacao financeira', NULL),
(UUID(), '60', 'Coordenador de Obras', 'coordenador de obras', NULL),
(UUID(), '145', 'Estagiário de TI', 'estagiario de ti', NULL),
(UUID(), '27', 'Analista Fiscal', 'analista fiscal', NULL),
(UUID(), '83', 'Estagiário de Engenharia', 'estagiario de engenharia', NULL),
(UUID(), '16', 'Analista de Infraestrutura', 'analista de infraestrutura', NULL),
(UUID(), '41', 'Assistente Fiscal', 'assistente fiscal', NULL),
(UUID(), '157', 'Assistente de Recursos Humanos', 'assistente de recursos humanos', NULL),
(UUID(), '151', 'Gerente de Crédito Imobiliário', 'gerente de credito imobiliario', NULL),
(UUID(), '81', 'Estagiário de Arquitetura e Urbanismo', 'estagiario de arquitetura e urbanismo', NULL),
(UUID(), '110', 'Piloto de Aeronave', 'piloto de aeronave', NULL),
(UUID(), '24', 'Analista de Sistemas', 'analista de sistemas', NULL),
(UUID(), '100', 'Meio Oficial de Carpinteiro', 'meio oficial de carpinteiro', NULL),
(UUID(), '127', 'Coordenador de Projetos Executivos', 'coordenador de projetos executivos', NULL),
(UUID(), '127', 'Coordenador de Projetos', 'coordenador de projetos', NULL),
(UUID(), '38', 'Assistente de Estruturas e Geotecnia', 'assistente de estruturas e geotecnia', NULL),
(UUID(), '5', 'Supervisor de Contas a Pagar', 'supervisor de contas a pagar', NULL),
(UUID(), '65', 'Desenvolvedor de Sistemas', 'desenvolvedor de sistemas', NULL),
(UUID(), '93', 'Supervisor de Conciliação', 'supervisor de conciliacao', NULL),
(UUID(), '122', 'Supervisor de Controle Tecnológico', 'supervisor de controle tecnologico', NULL),
(UUID(), '50', 'Auxiliar Financeiro', 'auxiliar financeiro', NULL),
(UUID(), '161', 'Coordenador de Contratação de Empreendimento', 'coordenador de contratacao de empreendimento', NULL),
(UUID(), '71', 'Encarregado Administrativo', 'encarregado administrativo', NULL),
(UUID(), '79', 'Gerente de Segurança do Trabalho', 'gerente de seguranca do trabalho', NULL),
(UUID(), '147', 'Analista de Planejamento e Controle', 'analista de planejamento e controle', NULL),
(UUID(), '40', 'Assistente Financeiro', 'assistente financeiro', NULL),
(UUID(), '146', 'Supervisor de Relacionamento com Cliente', 'supervisor de relacionamento com cliente', NULL),
(UUID(), '96', 'Instalador de Piso', 'instalador de piso', NULL),
(UUID(), '107', 'Operador de Mini Pá Carregadeira', 'operador de mini pa carregadeira', NULL),
(UUID(), '154', 'Gerente Administrativo', 'gerente administrativo', NULL),
(UUID(), '34', 'Assistente de Arquitetura', 'assistente de arquitetura', NULL),
(UUID(), '98', 'Marceneiro', 'marceneiro', NULL),
(UUID(), '149', 'Gerente de Planejamento e Controle', 'gerente de planejamento e controle', NULL),
(UUID(), '90', 'Gerente da Qualidade', 'gerente da qualidade', NULL),
(UUID(), '86', 'Estagiário Financeiro', 'estagiario financeiro', NULL),
(UUID(), '31', 'Assessor de Diretoria', 'assessor de diretoria', NULL),
(UUID(), '120', 'Supervisor Comercial', 'supervisor comercial', NULL),
(UUID(), '14', 'Analista de DSE', 'analista de dse', NULL),
(UUID(), '144', 'Supervisor de Departamento Pessoal', 'supervisor de departamento pessoal', NULL),
(UUID(), '72', 'Encarregado de Almoxarifado', 'encarregado de almoxarifado', NULL),
(UUID(), '1', 'Conselheiro Administrativo Estratégico', 'conselheiro administrativo estrategico', NULL),
(UUID(), '93', 'Gerente Financeiro', 'gerente financeiro', NULL),
(UUID(), '9', 'Coordenador de ArchViz', 'coordenador de archviz', NULL),
(UUID(), '40', 'Assistente Comercial', 'assistente comercial', NULL),
(UUID(), '36', 'Assistente de Compras', 'assistente de compras', NULL),
(UUID(), '35', 'Assistente de Atendimento', 'assistente de atendimento', NULL),
(UUID(), '162', 'Estagiário Fiscal', 'estagiario fiscal', NULL),
(UUID(), '143', 'Coordenador de Departamento Pessoal', 'coordenador de departamento pessoal', NULL),
(UUID(), '125', 'Supervisor Fiscal', 'supervisor fiscal', NULL),
(UUID(), '59', 'Coordenador de Cobrança', 'coordenador de cobranca', NULL),
(UUID(), '156', 'Gerente de Suprimentos', 'gerente de suprimentos', NULL),
(UUID(), '26', 'Supervisor de Contas a Receber', 'supervisor de contas a receber', NULL),
(UUID(), '84', 'Estagiário de Orçamentos', 'estagiario de orcamentos', NULL),
(UUID(), '137', 'Assistente Contábil', 'assistente contabil', NULL),
(UUID(), '12', 'Analista de Contratação PJ', 'analista de contratacao pj', NULL),
(UUID(), 'PJUR100', 'Coordenador Nacional de Vendas', 'coordenador nacional de vendas', NULL),
(UUID(), 'PJUR101', 'Coordenador de Instalações', 'coordenador de instalacoes', NULL),
(UUID(), 'PJUR102', 'Diretor Contábil', 'diretor contabil', NULL),
(UUID(), 'PJUR103', 'Gerente Nacional de Vendas', 'gerente nacional de vendas', NULL),
(UUID(), 'PJUR104', 'Diretor de Engenharia', 'diretor de engenharia', NULL),
(UUID(), 'PJUR105', 'Analista de Licenciamento', 'analista de licenciamento', NULL),
(UUID(), 'PJUR106', 'Diretor de Tecnologia da Informação', 'diretor de tecnologia da informacao', NULL),
(UUID(), 'PJUR107', 'Gerente de Cobrança', 'gerente de cobranca', NULL),
(UUID(), 'PJUR110', 'Coordenador de Marketing', 'coordenador de marketing', NULL),
(UUID(), 'PJUR112', 'Coordenador de Novos Negócios', 'coordenador de novos negocios', NULL),
(UUID(), 'PJUR113', 'Gerente de Marketing', 'gerente de marketing', NULL),
(UUID(), 'PJUR115', 'Captador de Leads', 'captador de leads', NULL),
(UUID(), 'PJUR116', 'Diretor de Desenvolvimento Imobiliário', 'diretor de desenvolvimento imobiliario', NULL),
(UUID(), 'PJUR117', 'Gestor de Permutas e Recompras', 'gestor de permutas e recompras', NULL),
(UUID(), 'PJUR118', 'Head de Processos e Inovação', 'head de processos e inovacao', NULL),
(UUID(), 'PJUR119', 'Gerente de Vendas Online', 'gerente de vendas online', NULL),
(UUID(), 'PJUR121', 'Diretor de Governança e Gestão Administrativa', 'diretor de governanca e gestao administrativa', NULL),
(UUID(), 'PJUR122', 'Diretor Comercial', 'diretor comercial', NULL),
(UUID(), 'PJUR123', 'Gerente de Novos Negócios', 'gerente de novos negocios', NULL),
(UUID(), 'PJUR124', 'Vice-Diretor Comercial', 'vice-diretor comercial', NULL),
(UUID(), 'PJUR125', 'Coordenador Fiscal', 'coordenador fiscal', NULL),
(UUID(), 'PJUR126', 'Coordenador de Facilities', 'coordenador de facilities', NULL),
(UUID(), 'PJUR127', 'Diretor Jurídico', 'diretor juridico', NULL),
(UUID(), 'PJUR129', 'CFO', 'cfo', NULL),
(UUID(), '158', 'Estagiário de Engenharia de Produção', 'estagiario de engenharia de producao', NULL),
(UUID(), '74', 'Encarregado de Armador', 'encarregado de armador', NULL),
(UUID(), '80', 'Engenheiro Eletricista', 'engenheiro eletricista', NULL),
(UUID(), '73', 'Encarregado de Acabamento', 'encarregado de acabamento', NULL),
(UUID(), '164', 'Secretária Executiva', 'secretaria executiva', NULL);

CREATE TABLE _map_cargo_nh (cargo_norm VARCHAR(160), nh VARCHAR(20), KEY(cargo_norm), KEY(nh)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO _map_cargo_nh (cargo_norm, nh) VALUES
('servente de obra', 'NH544'),
('pedreiro de acabamento', 'NH522'),
('gesseiro', 'NH526'),
('almoxarife', 'NH536'),
('encarregado de instalacoes', 'NH511'),
('analista de planejamento financeiro', 'NH518'),
('armador', 'NH525'),
('servente de limpeza', 'NH544'),
('porteiro', 'NH543'),
('mestre de obra', 'NH512'),
('sinaleiro', 'NH540'),
('encarregado de carpinteiro', 'NH511'),
('operador de cremalheira', 'NH532'),
('operador de betoneira', 'NH532'),
('encarregado de obra', 'NH511'),
('tecnico de seguranca do trabalho', 'NH521'),
('assistente administrativo', 'NH534'),
('assistente de planejamento e controle', 'NH534'),
('servente de limpeza b', 'NH544'),
('supervisor de seguranca do trabalho', 'NH510'),
('aprendiz', 'NH542'),
('encanador', 'NH528'),
('auxiliar fiscal', 'NH538'),
('auxiliar administrativo', 'NH538'),
('engenheiro civil', 'NH516'),
('tecnico de engenharia civil', 'NH521'),
('assistente de engenharia', 'NH534'),
('coordenador de suprimentos', 'NH506'),
('advogado', 'NH513'),
('assistente de conciliacao financeira', 'NH534'),
('analista de arquitetura', 'NH518'),
('comprador', 'NH519'),
('auxiliar de departamento pessoal', 'NH538'),
('assistente de departamento pessoal', 'NH534'),
('auxiliar de engenharia', 'NH538'),
('carpinteiro', 'NH523'),
('pedreiro de alvenaria', 'NH522'),
('tecnico orcamentista de obras', 'NH521'),
('gerente de planejamento financeiro', 'NH505'),
('analista financeiro', 'NH518'),
('auxiliar da qualidade', 'NH538'),
('analista de instalacoes', 'NH518'),
('assistente da qualidade', 'NH534'),
('analista contabil', 'NH518'),
('analista da qualidade', 'NH518'),
('tecnico de obras civis', 'NH521'),
('designer grafico', 'NH520'),
('diretor de suprimentos', 'NH503'),
('analista de cobranca', 'NH518'),
('eletricista de instalacoes', 'NH530'),
('bombeiro hidraulico', 'NH529'),
('auxiliar de almoxarifado', 'NH538'),
('gerente de projetos executivos', 'NH505'),
('analista administrativo', 'NH518'),
('assistente de compatibilizacao', 'NH534'),
('analista de recursos humanos', 'NH518'),
('analista de assistencia tecnica', 'NH518'),
('analista de departamento pessoal', 'NH518'),
('analista de meio ambiente', 'NH518'),
('estagiario de direito', 'NH541'),
('gerente de arquitetura e produto', 'NH505'),
('analista de marketing', 'NH518'),
('gerente corporativo de ti', 'NH505'),
('presidente', 'NH500'),
('pintor', 'NH527'),
('operador de grua', 'NH532'),
('analista de conciliacao financeira', 'NH518'),
('coordenador de obras', 'NH506'),
('estagiario de ti', 'NH541'),
('analista fiscal', 'NH518'),
('estagiario de engenharia', 'NH541'),
('analista de infraestrutura', 'NH518'),
('assistente fiscal', 'NH534'),
('assistente de recursos humanos', 'NH534'),
('gerente de credito imobiliario', 'NH505'),
('estagiario de arquitetura e urbanismo', 'NH541'),
('piloto de aeronave', 'NH517'),
('analista de sistemas', 'NH518'),
('meio oficial de carpinteiro', 'NH539'),
('coordenador de projetos executivos', 'NH506'),
('coordenador de projetos', 'NH506'),
('assistente de estruturas e geotecnia', 'NH534'),
('supervisor de contas a pagar', 'NH510'),
('desenvolvedor de sistemas', 'NH515'),
('supervisor de conciliacao', 'NH510'),
('supervisor de controle tecnologico', 'NH510'),
('auxiliar financeiro', 'NH538'),
('coordenador de contratacao de empreendimento', 'NH506'),
('encarregado administrativo', 'NH511'),
('gerente de seguranca do trabalho', 'NH505'),
('analista de planejamento e controle', 'NH518'),
('assistente financeiro', 'NH534'),
('supervisor de relacionamento com cliente', 'NH510'),
('instalador de piso', 'NH531'),
('operador de mini pa carregadeira', 'NH532'),
('gerente administrativo', 'NH505'),
('assistente de arquitetura', 'NH534'),
('marceneiro', 'NH524'),
('gerente de planejamento e controle', 'NH505'),
('gerente da qualidade', 'NH505'),
('estagiario financeiro', 'NH541'),
('assessor de diretoria', 'NH533'),
('supervisor comercial', 'NH510'),
('analista de dse', 'NH518'),
('supervisor de departamento pessoal', 'NH510'),
('encarregado de almoxarifado', 'NH511'),
('conselheiro administrativo estrategico', 'NH500'),
('gerente financeiro', 'NH505'),
('coordenador de archviz', 'NH506'),
('assistente comercial', 'NH534'),
('assistente de compras', 'NH534'),
('assistente de atendimento', 'NH534'),
('estagiario fiscal', 'NH541'),
('coordenador de departamento pessoal', 'NH506'),
('supervisor fiscal', 'NH510'),
('coordenador de cobranca', 'NH506'),
('gerente de suprimentos', 'NH505'),
('supervisor de contas a receber', 'NH510'),
('estagiario de orcamentos', 'NH541'),
('assistente contabil', 'NH534'),
('analista de contratacao pj', 'NH518'),
('coordenador nacional de vendas', 'NH506'),
('coordenador de instalacoes', 'NH506'),
('diretor contabil', 'NH503'),
('gerente nacional de vendas', 'NH506'),
('diretor de engenharia', 'NH503'),
('analista de licenciamento', 'NH518'),
('diretor de tecnologia da informacao', 'NH503'),
('gerente de cobranca', 'NH505'),
('coordenador de marketing', 'NH506'),
('coordenador de novos negocios', 'NH506'),
('gerente de marketing', 'NH505'),
('captador de leads', 'NH535'),
('diretor de desenvolvimento imobiliario', 'NH503'),
('gestor de permutas e recompras', 'NH508'),
('head de processos e inovacao', 'NH509'),
('gerente de vendas online', 'NH505'),
('diretor de governanca e gestao administrativa', 'NH503'),
('diretor comercial', 'NH503'),
('gerente de novos negocios', 'NH505'),
('vice-diretor comercial', 'NH504'),
('coordenador fiscal', 'NH506'),
('coordenador de facilities', 'NH506'),
('diretor juridico', 'NH503'),
('cfo', 'NH502'),
('estagiario de engenharia de producao', 'NH541'),
('encarregado de armador', 'NH511'),
('engenheiro eletricista', 'NH516'),
('encarregado de acabamento', 'NH511'),
('secretaria executiva', 'NH537');
UPDATE cargo c JOIN _map_cargo_nh t ON t.cargo_norm = c.nome_normalizado JOIN nivel_hierarquico nh ON nh.codigo_nh = t.nh SET c.nivel_id = nh.id;
DROP TABLE IF EXISTS _map_cargo_nh;
