-- ============================================================================
-- Migração 10 — Cargo identificado pelo CÓDIGO oficial do DP + nome do DP
-- ============================================================================
-- Decisões (com o usuário, 2026-07):
--  * codigo_cargo_dp passa a ser a IDENTIDADE do cargo (ÚNICO; NULL para os
--    49 cargos legados fora da tabela oficial — casam por nome).
--  * O NOME do DP manda: o catálogo assume a grafia do extrato (inclusive
--    abreviações: "Analista Depart. Pessoal"). Rename automático também na
--    importação quando o código casa e o nome diverge.
--  * Assimilação de nível pela FAMÍLIA do nome (prefixo mais longo): aplicada
--    aos 7 sem nível com família reconhecível; "Administrador" e "Ajudante de
--    Eletricista" ficam sem nível por decisão (classificar em Catálogos).
--  * Divergências pré-existentes mantidas por decisão: "Conselheiro Adm.
--    Estratégico"→família Presidente e "Gerente Nacional de Vendas"→família
--    Coordenador.
-- Vínculos colaborador.cargo_id preservados (ids não mudam).
-- Matching de código na importação é por dígitos SEM zeros à esquerda
-- ("089" ≡ "89"); a grafia oficial fica gravada como veio do DP.
-- ============================================================================

UPDATE cargo SET
  codigo_cargo_dp = CASE nome_normalizado
    WHEN 'administrador' THEN '001'
    WHEN 'advogado' THEN '002'
    WHEN 'ajudante de eletricista' THEN '003'
    WHEN 'almoxarife' THEN '004'
    WHEN 'analista administrativo' THEN '005'
    WHEN 'analista de assistencia tecnica' THEN '006'
    WHEN 'analista contabil' THEN '007'
    WHEN 'analista da qualidade' THEN '008'
    WHEN 'analista de arquitetura' THEN '009'
    WHEN 'analista de cobranca' THEN '011'
    WHEN 'analista de contratacao pj' THEN '012'
    WHEN 'analista de dse' THEN '014'
    WHEN 'gerente de suprimentos' THEN '0156'
    WHEN 'analista de infraestrutura' THEN '016'
    WHEN 'analista de marketing' THEN '017'
    WHEN 'analista de planejamento financeiro' THEN '019'
    WHEN 'analista de recursos humanos' THEN '023'
    WHEN 'analista de sistemas' THEN '024'
    WHEN 'analista de departamento pessoal' THEN '025'
    WHEN 'analista financeiro' THEN '026'
    WHEN 'analista fiscal' THEN '027'
    WHEN 'aprendiz' THEN '028'
    WHEN 'armador' THEN '029'
    WHEN 'arquiteto' THEN '030'
    WHEN 'assessor de diretoria' THEN '031'
    WHEN 'assistente administrativo' THEN '032'
    WHEN 'assistente da qualidade' THEN '033'
    WHEN 'assistente de arquitetura' THEN '034'
    WHEN 'assistente de atendimento' THEN '035'
    WHEN 'assistente de compras' THEN '036'
    WHEN 'assistente de engenharia' THEN '038'
    WHEN 'assistente de departamento pessoal' THEN '039'
    WHEN 'assistente financeiro' THEN '040'
    WHEN 'assistente fiscal' THEN '041'
    WHEN 'assistente de planejamento e controle' THEN '042'
    WHEN 'auxiliar administrativo' THEN '043'
    WHEN 'auxiliar da qualidade' THEN '045'
    WHEN 'auxiliar de almoxarifado' THEN '046'
    WHEN 'auxiliar de engenharia' THEN '048'
    WHEN 'auxiliar de departamento pessoal' THEN '049'
    WHEN 'auxiliar financeiro' THEN '050'
    WHEN 'bombeiro hidraulico' THEN '053'
    WHEN 'carpinteiro' THEN '054'
    WHEN 'comprador' THEN '055'
    WHEN 'coordenador de cobranca' THEN '059'
    WHEN 'coordenador de obras' THEN '060'
    WHEN 'coordenador de suprimentos' THEN '061'
    WHEN 'desenvolvedor de sistemas' THEN '065'
    WHEN 'designer grafico' THEN '066'
    WHEN 'diretor financeiro' THEN '068'
    WHEN 'eletricista de instalacoes' THEN '069'
    WHEN 'encanador' THEN '070'
    WHEN 'encarregado administrativo' THEN '071'
    WHEN 'encarregado de almoxarifado' THEN '072'
    WHEN 'encarregado de acabamento' THEN '073'
    WHEN 'encarregado de armador' THEN '074'
    WHEN 'encarregado de carpinteiro' THEN '075'
    WHEN 'encarregado de instalacoes' THEN '076'
    WHEN 'encarregado de obra' THEN '077'
    WHEN 'engenheiro civil' THEN '078'
    WHEN 'engenheiro de seg do trabalho' THEN '079'
    WHEN 'engenheiro eletricista' THEN '080'
    WHEN 'estagiario de arquitetura e urbanismo' THEN '081'
    WHEN 'estagiario de direito' THEN '082'
    WHEN 'estagiario de engenharia' THEN '083'
    WHEN 'estagiario de orcamentos' THEN '084'
    WHEN 'estagiario financeiro' THEN '086'
    WHEN 'estagiario seg. trabalho' THEN '087'
    WHEN 'gerente corporativo de ti' THEN '089'
    WHEN 'gerente da qualidade' THEN '090'
    WHEN 'gerente de projetos' THEN '092'
    WHEN 'gerente financeiro' THEN '093'
    WHEN 'gesseiro' THEN '095'
    WHEN 'instalador de piso' THEN '096'
    WHEN 'marceneiro' THEN '098'
    WHEN 'meio oficial de carpinteiro' THEN '100'
    WHEN 'mestre de obra' THEN '101'
    WHEN 'operador de betoneira' THEN '103'
    WHEN 'operador de cremalheira' THEN '104'
    WHEN 'operador de grua' THEN '105'
    WHEN 'operador de mini pa carregadeira' THEN '107'
    WHEN 'pedreiro de acabamento' THEN '108'
    WHEN 'pedreiro de alvenaria' THEN '109'
    WHEN 'piloto de aeronave' THEN '110'
    WHEN 'pintor' THEN '111'
    WHEN 'porteiro' THEN '112'
    WHEN 'servente de limpeza' THEN '115'
    WHEN 'servente de limpeza b' THEN '116'
    WHEN 'servente de obra' THEN '117'
    WHEN 'sinaleiro' THEN '118'
    WHEN 'supervisor comercial' THEN '120'
    WHEN 'supervisor financeiro' THEN '121'
    WHEN 'supervisor de controle tecnologico' THEN '122'
    WHEN 'supervisor fiscal' THEN '125'
    WHEN 'supervisor de seguranca do trabalho' THEN '126'
    WHEN 'tecnico de engenharia civil' THEN '127'
    WHEN 'tecnico de obras civis' THEN '130'
    WHEN 'tecnico orcamentista de obras' THEN '131'
    WHEN 'tecnico de seguranca do trabalho' THEN '132'
    WHEN 'coordenador de departamento pessoal' THEN '143'
    WHEN 'supervisor de departamento pessoal' THEN '144'
    WHEN 'estagiario de ti' THEN '145'
    WHEN 'supervisor de relacionamento com cliente' THEN '146'
    WHEN 'analista de planejamento e controle' THEN '147'
    WHEN 'gerente de planejamento e controle' THEN '149'
    WHEN 'gerente de credito imobiliario' THEN '151'
    WHEN 'gerente administrativo' THEN '154'
    WHEN 'assistente de recursos humanos' THEN '157'
    WHEN 'coordenador de contratacao de empreendimento' THEN '161'
    WHEN 'analista de desenvolvimento imobiliario' THEN '163'
    WHEN 'secretaria executiva' THEN '164'
    ELSE NULL END,
  nome = CASE nome_normalizado
    WHEN 'administrador' THEN 'Administrador'
    WHEN 'advogado' THEN 'Advogado'
    WHEN 'ajudante de eletricista' THEN 'Ajudante de Eletricista'
    WHEN 'almoxarife' THEN 'Almoxarife'
    WHEN 'analista administrativo' THEN 'Analista Administrativo'
    WHEN 'analista de assistencia tecnica' THEN 'Analista Assistencia Tecnica'
    WHEN 'analista contabil' THEN 'Analista Contabil'
    WHEN 'analista da qualidade' THEN 'Analista da Qualidade'
    WHEN 'analista de arquitetura' THEN 'Analista de Arquitetura'
    WHEN 'analista de cobranca' THEN 'Analista de Cobranca'
    WHEN 'analista de contratacao pj' THEN 'Analista de Contratacao PJ'
    WHEN 'analista de dse' THEN 'Analista de DSE'
    WHEN 'gerente de suprimentos' THEN 'Gerente de Suprimentos'
    WHEN 'analista de infraestrutura' THEN 'Analista de Infraestrutura'
    WHEN 'analista de marketing' THEN 'Analista de Marketing'
    WHEN 'analista de planejamento financeiro' THEN 'Analista de Plan Financeiro'
    WHEN 'analista de recursos humanos' THEN 'Analista de Rec. Humanos'
    WHEN 'analista de sistemas' THEN 'Analista de Sistemas'
    WHEN 'analista de departamento pessoal' THEN 'Analista Depart. Pessoal'
    WHEN 'analista financeiro' THEN 'Analista Financeiro'
    WHEN 'analista fiscal' THEN 'Analista Fiscal'
    WHEN 'aprendiz' THEN 'Aprendiz'
    WHEN 'armador' THEN 'Armador'
    WHEN 'arquiteto' THEN 'Arquiteto'
    WHEN 'assessor de diretoria' THEN 'Assessor Diretoria'
    WHEN 'assistente administrativo' THEN 'Assistente Administrativo'
    WHEN 'assistente da qualidade' THEN 'Assistente da Qualidade'
    WHEN 'assistente de arquitetura' THEN 'Assistente de Arquitetura'
    WHEN 'assistente de atendimento' THEN 'Assistente de Atendimento'
    WHEN 'assistente de compras' THEN 'Assistente de Compras'
    WHEN 'assistente de engenharia' THEN 'Assistente de Engenharia'
    WHEN 'assistente de departamento pessoal' THEN 'Assistente Depart. Pessoal'
    WHEN 'assistente financeiro' THEN 'Assistente Financeiro'
    WHEN 'assistente fiscal' THEN 'Assistente Fiscal'
    WHEN 'assistente de planejamento e controle' THEN 'Assistente Plan e Controle'
    WHEN 'auxiliar administrativo' THEN 'Auxiliar Administrativo'
    WHEN 'auxiliar da qualidade' THEN 'Auxiliar da Qualidade'
    WHEN 'auxiliar de almoxarifado' THEN 'Auxiliar de Almoxarifado'
    WHEN 'auxiliar de engenharia' THEN 'Auxiliar de Engenharia'
    WHEN 'auxiliar de departamento pessoal' THEN 'Auxiliar Depart. Pessoal'
    WHEN 'auxiliar financeiro' THEN 'Auxiliar Fiinanceiro'
    WHEN 'bombeiro hidraulico' THEN 'Bombeiro Hidraulico'
    WHEN 'carpinteiro' THEN 'Carpinteiro'
    WHEN 'comprador' THEN 'Comprador'
    WHEN 'coordenador de cobranca' THEN 'Coordenador de Cobrança'
    WHEN 'coordenador de obras' THEN 'Coordenador de Obras'
    WHEN 'coordenador de suprimentos' THEN 'Coordenador de Suprimentos'
    WHEN 'desenvolvedor de sistemas' THEN 'Desenvolvedor de Sistemas'
    WHEN 'designer grafico' THEN 'Designer Grafico'
    WHEN 'diretor financeiro' THEN 'Diretor Financeiro'
    WHEN 'eletricista de instalacoes' THEN 'Eletricista de Instalações'
    WHEN 'encanador' THEN 'Encanador'
    WHEN 'encarregado administrativo' THEN 'Encarregado Administrativo'
    WHEN 'encarregado de almoxarifado' THEN 'Encarregado Almoxarifado'
    WHEN 'encarregado de acabamento' THEN 'Encarregado de Acabamento'
    WHEN 'encarregado de armador' THEN 'Encarregado de Armador'
    WHEN 'encarregado de carpinteiro' THEN 'Encarregado de Carpinteiro'
    WHEN 'encarregado de instalacoes' THEN 'Encarregado de Instalações'
    WHEN 'encarregado de obra' THEN 'Encarregado de Obra'
    WHEN 'engenheiro civil' THEN 'Engenheiro Civil'
    WHEN 'engenheiro de seg do trabalho' THEN 'Engenheiro de Seg do Trabalho'
    WHEN 'engenheiro eletricista' THEN 'Engenheiro Eletricista'
    WHEN 'estagiario de arquitetura e urbanismo' THEN 'Estagiario Arquitetura e urban'
    WHEN 'estagiario de direito' THEN 'Estagiario de Direito'
    WHEN 'estagiario de engenharia' THEN 'Estagiario de Engenharia'
    WHEN 'estagiario de orcamentos' THEN 'Estagiario de Orcamentos'
    WHEN 'estagiario financeiro' THEN 'Estagiario Financeiro'
    WHEN 'estagiario seg. trabalho' THEN 'Estagiario Seg. Trabalho'
    WHEN 'gerente corporativo de ti' THEN 'Gerente Corporativo de TI'
    WHEN 'gerente da qualidade' THEN 'Gerente da Qualidade'
    WHEN 'gerente de projetos' THEN 'Gerente de Projetos'
    WHEN 'gerente financeiro' THEN 'Gerente Financeiro'
    WHEN 'gesseiro' THEN 'Gesseiro'
    WHEN 'instalador de piso' THEN 'Instalador de Piso'
    WHEN 'marceneiro' THEN 'Marceneiro'
    WHEN 'meio oficial de carpinteiro' THEN 'Meio Oficial Carpinteiro'
    WHEN 'mestre de obra' THEN 'Mestre de Obra'
    WHEN 'operador de betoneira' THEN 'Operador de Betoneira'
    WHEN 'operador de cremalheira' THEN 'Operador de Cremalheira'
    WHEN 'operador de grua' THEN 'Operador de Grua'
    WHEN 'operador de mini pa carregadeira' THEN 'Operador Mini PA Carregad.'
    WHEN 'pedreiro de acabamento' THEN 'Pedreiro de Acabamento'
    WHEN 'pedreiro de alvenaria' THEN 'Pedreiro de Alvenaria'
    WHEN 'piloto de aeronave' THEN 'Piloto de Aeronave'
    WHEN 'pintor' THEN 'Pintor'
    WHEN 'porteiro' THEN 'Porteiro'
    WHEN 'servente de limpeza' THEN 'Servente de Limpeza'
    WHEN 'servente de limpeza b' THEN 'Servente de Limpeza B'
    WHEN 'servente de obra' THEN 'Servente de Obra'
    WHEN 'sinaleiro' THEN 'Sinaleiro'
    WHEN 'supervisor comercial' THEN 'Supervisor Comercial'
    WHEN 'supervisor financeiro' THEN 'Supervisor Financeiro'
    WHEN 'supervisor de controle tecnologico' THEN 'Supervisor Contr. Tecnolog.'
    WHEN 'supervisor fiscal' THEN 'Supervisor Fiscal'
    WHEN 'supervisor de seguranca do trabalho' THEN 'Supervisor SEG. Trabalho'
    WHEN 'tecnico de engenharia civil' THEN 'Tecnico de Engenharia Civil'
    WHEN 'tecnico de obras civis' THEN 'Tecnico de Obras Civis'
    WHEN 'tecnico orcamentista de obras' THEN 'Tecnico Orçamentista Obras'
    WHEN 'tecnico de seguranca do trabalho' THEN 'Tecnico SEG. Trabalho'
    WHEN 'coordenador de departamento pessoal' THEN 'Coordenador(a) Departamento Pessoal'
    WHEN 'supervisor de departamento pessoal' THEN 'Supervisor(a) Departamento Pessoal'
    WHEN 'estagiario de ti' THEN 'Estagiario T.I'
    WHEN 'supervisor de relacionamento com cliente' THEN 'Supervisor(a) Relacionamento com Cliente'
    WHEN 'analista de planejamento e controle' THEN 'Analista Planejamento e Controle'
    WHEN 'gerente de planejamento e controle' THEN 'Gerente de Planejamento e Controle'
    WHEN 'gerente de credito imobiliario' THEN 'Gerente de Credito Imobiliario'
    WHEN 'gerente administrativo' THEN 'Gerente Administrativo'
    WHEN 'assistente de recursos humanos' THEN 'Assistente de Recursos Humanos'
    WHEN 'coordenador de contratacao de empreendimento' THEN 'Coordenador (a) de Contratação de Empreendimento'
    WHEN 'analista de desenvolvimento imobiliario' THEN 'Analista de Desenvolvimento Imobiliário'
    WHEN 'secretaria executiva' THEN 'Secretaria Executiva'
    ELSE nome END,
  nome_normalizado = CASE nome_normalizado
    WHEN 'administrador' THEN 'administrador'
    WHEN 'advogado' THEN 'advogado'
    WHEN 'ajudante de eletricista' THEN 'ajudante de eletricista'
    WHEN 'almoxarife' THEN 'almoxarife'
    WHEN 'analista administrativo' THEN 'analista administrativo'
    WHEN 'analista de assistencia tecnica' THEN 'analista assistencia tecnica'
    WHEN 'analista contabil' THEN 'analista contabil'
    WHEN 'analista da qualidade' THEN 'analista da qualidade'
    WHEN 'analista de arquitetura' THEN 'analista de arquitetura'
    WHEN 'analista de cobranca' THEN 'analista de cobranca'
    WHEN 'analista de contratacao pj' THEN 'analista de contratacao pj'
    WHEN 'analista de dse' THEN 'analista de dse'
    WHEN 'gerente de suprimentos' THEN 'gerente de suprimentos'
    WHEN 'analista de infraestrutura' THEN 'analista de infraestrutura'
    WHEN 'analista de marketing' THEN 'analista de marketing'
    WHEN 'analista de planejamento financeiro' THEN 'analista de plan financeiro'
    WHEN 'analista de recursos humanos' THEN 'analista de rec. humanos'
    WHEN 'analista de sistemas' THEN 'analista de sistemas'
    WHEN 'analista de departamento pessoal' THEN 'analista depart. pessoal'
    WHEN 'analista financeiro' THEN 'analista financeiro'
    WHEN 'analista fiscal' THEN 'analista fiscal'
    WHEN 'aprendiz' THEN 'aprendiz'
    WHEN 'armador' THEN 'armador'
    WHEN 'arquiteto' THEN 'arquiteto'
    WHEN 'assessor de diretoria' THEN 'assessor diretoria'
    WHEN 'assistente administrativo' THEN 'assistente administrativo'
    WHEN 'assistente da qualidade' THEN 'assistente da qualidade'
    WHEN 'assistente de arquitetura' THEN 'assistente de arquitetura'
    WHEN 'assistente de atendimento' THEN 'assistente de atendimento'
    WHEN 'assistente de compras' THEN 'assistente de compras'
    WHEN 'assistente de engenharia' THEN 'assistente de engenharia'
    WHEN 'assistente de departamento pessoal' THEN 'assistente depart. pessoal'
    WHEN 'assistente financeiro' THEN 'assistente financeiro'
    WHEN 'assistente fiscal' THEN 'assistente fiscal'
    WHEN 'assistente de planejamento e controle' THEN 'assistente plan e controle'
    WHEN 'auxiliar administrativo' THEN 'auxiliar administrativo'
    WHEN 'auxiliar da qualidade' THEN 'auxiliar da qualidade'
    WHEN 'auxiliar de almoxarifado' THEN 'auxiliar de almoxarifado'
    WHEN 'auxiliar de engenharia' THEN 'auxiliar de engenharia'
    WHEN 'auxiliar de departamento pessoal' THEN 'auxiliar depart. pessoal'
    WHEN 'auxiliar financeiro' THEN 'auxiliar fiinanceiro'
    WHEN 'bombeiro hidraulico' THEN 'bombeiro hidraulico'
    WHEN 'carpinteiro' THEN 'carpinteiro'
    WHEN 'comprador' THEN 'comprador'
    WHEN 'coordenador de cobranca' THEN 'coordenador de cobranca'
    WHEN 'coordenador de obras' THEN 'coordenador de obras'
    WHEN 'coordenador de suprimentos' THEN 'coordenador de suprimentos'
    WHEN 'desenvolvedor de sistemas' THEN 'desenvolvedor de sistemas'
    WHEN 'designer grafico' THEN 'designer grafico'
    WHEN 'diretor financeiro' THEN 'diretor financeiro'
    WHEN 'eletricista de instalacoes' THEN 'eletricista de instalacoes'
    WHEN 'encanador' THEN 'encanador'
    WHEN 'encarregado administrativo' THEN 'encarregado administrativo'
    WHEN 'encarregado de almoxarifado' THEN 'encarregado almoxarifado'
    WHEN 'encarregado de acabamento' THEN 'encarregado de acabamento'
    WHEN 'encarregado de armador' THEN 'encarregado de armador'
    WHEN 'encarregado de carpinteiro' THEN 'encarregado de carpinteiro'
    WHEN 'encarregado de instalacoes' THEN 'encarregado de instalacoes'
    WHEN 'encarregado de obra' THEN 'encarregado de obra'
    WHEN 'engenheiro civil' THEN 'engenheiro civil'
    WHEN 'engenheiro de seg do trabalho' THEN 'engenheiro de seg do trabalho'
    WHEN 'engenheiro eletricista' THEN 'engenheiro eletricista'
    WHEN 'estagiario de arquitetura e urbanismo' THEN 'estagiario arquitetura e urban'
    WHEN 'estagiario de direito' THEN 'estagiario de direito'
    WHEN 'estagiario de engenharia' THEN 'estagiario de engenharia'
    WHEN 'estagiario de orcamentos' THEN 'estagiario de orcamentos'
    WHEN 'estagiario financeiro' THEN 'estagiario financeiro'
    WHEN 'estagiario seg. trabalho' THEN 'estagiario seg. trabalho'
    WHEN 'gerente corporativo de ti' THEN 'gerente corporativo de ti'
    WHEN 'gerente da qualidade' THEN 'gerente da qualidade'
    WHEN 'gerente de projetos' THEN 'gerente de projetos'
    WHEN 'gerente financeiro' THEN 'gerente financeiro'
    WHEN 'gesseiro' THEN 'gesseiro'
    WHEN 'instalador de piso' THEN 'instalador de piso'
    WHEN 'marceneiro' THEN 'marceneiro'
    WHEN 'meio oficial de carpinteiro' THEN 'meio oficial carpinteiro'
    WHEN 'mestre de obra' THEN 'mestre de obra'
    WHEN 'operador de betoneira' THEN 'operador de betoneira'
    WHEN 'operador de cremalheira' THEN 'operador de cremalheira'
    WHEN 'operador de grua' THEN 'operador de grua'
    WHEN 'operador de mini pa carregadeira' THEN 'operador mini pa carregad.'
    WHEN 'pedreiro de acabamento' THEN 'pedreiro de acabamento'
    WHEN 'pedreiro de alvenaria' THEN 'pedreiro de alvenaria'
    WHEN 'piloto de aeronave' THEN 'piloto de aeronave'
    WHEN 'pintor' THEN 'pintor'
    WHEN 'porteiro' THEN 'porteiro'
    WHEN 'servente de limpeza' THEN 'servente de limpeza'
    WHEN 'servente de limpeza b' THEN 'servente de limpeza b'
    WHEN 'servente de obra' THEN 'servente de obra'
    WHEN 'sinaleiro' THEN 'sinaleiro'
    WHEN 'supervisor comercial' THEN 'supervisor comercial'
    WHEN 'supervisor financeiro' THEN 'supervisor financeiro'
    WHEN 'supervisor de controle tecnologico' THEN 'supervisor contr. tecnolog.'
    WHEN 'supervisor fiscal' THEN 'supervisor fiscal'
    WHEN 'supervisor de seguranca do trabalho' THEN 'supervisor seg. trabalho'
    WHEN 'tecnico de engenharia civil' THEN 'tecnico de engenharia civil'
    WHEN 'tecnico de obras civis' THEN 'tecnico de obras civis'
    WHEN 'tecnico orcamentista de obras' THEN 'tecnico orcamentista obras'
    WHEN 'tecnico de seguranca do trabalho' THEN 'tecnico seg. trabalho'
    WHEN 'coordenador de departamento pessoal' THEN 'coordenador(a) departamento pessoal'
    WHEN 'supervisor de departamento pessoal' THEN 'supervisor(a) departamento pessoal'
    WHEN 'estagiario de ti' THEN 'estagiario t.i'
    WHEN 'supervisor de relacionamento com cliente' THEN 'supervisor(a) relacionamento com cliente'
    WHEN 'analista de planejamento e controle' THEN 'analista planejamento e controle'
    WHEN 'gerente de planejamento e controle' THEN 'gerente de planejamento e controle'
    WHEN 'gerente de credito imobiliario' THEN 'gerente de credito imobiliario'
    WHEN 'gerente administrativo' THEN 'gerente administrativo'
    WHEN 'assistente de recursos humanos' THEN 'assistente de recursos humanos'
    WHEN 'coordenador de contratacao de empreendimento' THEN 'coordenador (a) de contratacao de empreendimento'
    WHEN 'analista de desenvolvimento imobiliario' THEN 'analista de desenvolvimento imobiliario'
    WHEN 'secretaria executiva' THEN 'secretaria executiva'
    ELSE nome_normalizado END;
ALTER TABLE cargo ADD UNIQUE KEY uq_cargo_dp (codigo_cargo_dp);

-- assimilação de nível (família pelo nome) dos 7 sem nível
UPDATE cargo c
  JOIN nivel_hierarquico n ON n.familia = CASE c.nome_normalizado
    WHEN 'analista de desenvolvimento imobiliario' THEN 'Analista'
    WHEN 'arquiteto' THEN 'Arquiteto'
    WHEN 'diretor financeiro' THEN 'Diretor'
    WHEN 'engenheiro de seg do trabalho' THEN 'Engenheiro'
    WHEN 'estagiario seg. trabalho' THEN 'Estagiário'
    WHEN 'gerente de projetos' THEN 'Gerente'
    WHEN 'supervisor financeiro' THEN 'Supervisor'
    ELSE NULL END
   SET c.nivel_id = n.id
 WHERE c.nivel_id IS NULL;

-- Conferência: 111 com código (únicos), 49 sem, 2 sem nível
--   SELECT COUNT(*) FROM cargo WHERE codigo_cargo_dp IS NOT NULL;  -- 111
--   SELECT nome FROM cargo WHERE nivel_id IS NULL;                 -- os 2
